/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/http/src/http_module';
import * as import6 from '@angular/forms/src/directives';
import * as import7 from '@angular/forms/src/form_providers';
import * as import8 from 'ionic-angular/module';
import * as import9 from '@ionic/cloud-angular/dist/es5/index';
import * as import10 from '@angular/common/src/localization';
import * as import11 from 'ionic-angular/components/app/app';
import * as import12 from '@angular/core/src/application_init';
import * as import13 from '@angular/core/src/testability/testability';
import * as import14 from '@angular/core/src/application_ref';
import * as import15 from '@angular/core/src/linker/compiler';
import * as import16 from 'ionic-angular/gestures/gesture-config';
import * as import17 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import18 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import19 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import20 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import21 from '@angular/core/src/linker/view_utils';
import * as import22 from '@angular/platform-browser/src/browser/title';
import * as import23 from '@angular/http/src/backends/browser_xhr';
import * as import24 from '@angular/http/src/base_response_options';
import * as import25 from '@angular/http/src/backends/xhr_backend';
import * as import26 from '@angular/http/src/base_request_options';
import * as import27 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import28 from '@angular/forms/src/form_builder';
import * as import29 from 'ionic-angular/components/action-sheet/action-sheet';
import * as import30 from 'ionic-angular/components/alert/alert';
import * as import31 from 'ionic-angular/util/events';
import * as import32 from 'ionic-angular/util/form';
import * as import33 from 'ionic-angular/util/haptic';
import * as import34 from 'ionic-angular/gestures/gesture-controller';
import * as import35 from 'ionic-angular/util/keyboard';
import * as import36 from 'ionic-angular/components/loading/loading';
import * as import37 from '@angular/common/src/location/location';
import * as import38 from 'ionic-angular/components/menu/menu-controller';
import * as import39 from 'ionic-angular/components/modal/modal';
import * as import40 from 'ionic-angular/components/picker/picker';
import * as import41 from 'ionic-angular/components/popover/popover';
import * as import42 from 'ionic-angular/components/tap-click/tap-click';
import * as import43 from 'ionic-angular/components/toast/toast';
import * as import44 from 'ionic-angular/translation/translate';
import * as import45 from 'ionic-angular/transitions/transition-controller';
import * as import46 from '../providers/auth-data';
import * as import47 from 'ionic-native/dist/es5/plugins/facebook';
import * as import48 from '@ionic/storage/es2015/storage';
import * as import49 from '@angular/core/src/di/injector';
import * as import50 from '../node_modules/ionic-angular/components/action-sheet/action-sheet-component.ngfactory';
import * as import51 from '../node_modules/ionic-angular/components/alert/alert-component.ngfactory';
import * as import52 from '../node_modules/ionic-angular/components/app/app-root.ngfactory';
import * as import53 from '../node_modules/ionic-angular/components/loading/loading-component.ngfactory';
import * as import54 from '../node_modules/ionic-angular/components/modal/modal-component.ngfactory';
import * as import55 from '../node_modules/ionic-angular/components/picker/picker-component.ngfactory';
import * as import56 from '../node_modules/ionic-angular/components/popover/popover-component.ngfactory';
import * as import57 from '../node_modules/ionic-angular/components/toast/toast-component.ngfactory';
import * as import58 from './app.component.ngfactory';
import * as import59 from '../pages/login/login.ngfactory';
import * as import60 from '../pages/dashboard/dashboard.ngfactory';
import * as import61 from '../pages/category/category.ngfactory';
import * as import62 from '../pages/membership/membership.ngfactory';
import * as import63 from '@angular/core/src/application_tokens';
import * as import64 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import65 from '@angular/platform-browser/src/dom/events/key_events';
import * as import66 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import67 from '@angular/core/src/zone/ng_zone';
import * as import68 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import69 from './app.component';
import * as import70 from '@angular/common/src/location/platform_location';
import * as import71 from '@angular/common/src/location/location_strategy';
import * as import72 from 'ionic-angular/navigation/url-serializer';
import * as import73 from 'ionic-angular/navigation/deep-linker';
import * as import74 from 'ionic-angular/platform/query-params';
import * as import75 from 'ionic-angular/platform/platform-registry';
import * as import76 from 'ionic-angular/platform/platform';
import * as import77 from 'ionic-angular/config/config';
import * as import78 from 'ionic-angular/config/mode-registry';
import * as import79 from 'ionic-angular/transitions/transition-registry';
import * as import80 from '@angular/core/src/console';
import * as import81 from '@angular/core/src/i18n/tokens';
import * as import82 from '@angular/core/src/error_handler';
import * as import83 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import84 from '@angular/platform-browser/src/dom/animation_driver';
import * as import85 from '@angular/core/src/render/api';
import * as import86 from '@angular/core/src/security';
import * as import87 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import88 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import89 from '@angular/http/src/interfaces';
import * as import90 from '@angular/http/src/http';
import * as import91 from 'ionic-angular/components/app/app-root';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _HttpModule_3:import5.HttpModule;
  _InternalFormsSharedModule_4:import6.InternalFormsSharedModule;
  _FormsModule_5:import7.FormsModule;
  _ReactiveFormsModule_6:import7.ReactiveFormsModule;
  _IonicModule_7:import8.IonicModule;
  _CloudModule_8:import9.CloudModule;
  _AppModule_9:import1.AppModule;
  __LOCALE_ID_10:any;
  __NgLocalization_11:import10.NgLocaleLocalization;
  _ErrorHandler_12:any;
  _ConfigToken_13:any;
  _UrlToken_14:any;
  _QueryParams_15:any;
  _PlatformConfigToken_16:any;
  _UserAgentToken_17:any;
  _NavigatorPlatformToken_18:any;
  _DocumentDirToken_19:any;
  _DocLangToken_20:any;
  _Platform_21:any;
  _Config_22:any;
  _App_23:import11.App;
  _APP_INITIALIZER_24:any[];
  _ApplicationInitStatus_25:import12.ApplicationInitStatus;
  _Testability_26:import13.Testability;
  _ApplicationRef__27:import14.ApplicationRef_;
  __ApplicationRef_28:any;
  __Compiler_29:import15.Compiler;
  __APP_ID_30:any;
  __DOCUMENT_31:any;
  __HAMMER_GESTURE_CONFIG_32:import16.IonicGestureConfig;
  __EVENT_MANAGER_PLUGINS_33:any[];
  __EventManager_34:import17.EventManager;
  __DomSharedStylesHost_35:import18.DomSharedStylesHost;
  __AnimationDriver_36:any;
  __DomRootRenderer_37:import19.DomRootRenderer_;
  __RootRenderer_38:any;
  __DomSanitizer_39:import20.DomSanitizerImpl;
  __Sanitizer_40:any;
  __ViewUtils_41:import21.ViewUtils;
  __IterableDiffers_42:any;
  __KeyValueDiffers_43:any;
  __SharedStylesHost_44:any;
  __Title_45:import22.Title;
  __BrowserXhr_46:import23.BrowserXhr;
  __ResponseOptions_47:import24.BaseResponseOptions;
  __XSRFStrategy_48:any;
  __XHRBackend_49:import25.XHRBackend;
  __RequestOptions_50:import26.BaseRequestOptions;
  __Http_51:any;
  __RadioControlRegistry_52:import27.RadioControlRegistry;
  __FormBuilder_53:import28.FormBuilder;
  __AppRootToken_54:any;
  __DeepLinkConfigToken_55:any;
  __ActionSheetController_56:import29.ActionSheetController;
  __AlertController_57:import30.AlertController;
  __Events_58:import31.Events;
  __Form_59:import32.Form;
  __Haptic_60:import33.Haptic;
  __GestureController_61:import34.GestureController;
  __Keyboard_62:import35.Keyboard;
  __LoadingController_63:import36.LoadingController;
  __LocationStrategy_64:any;
  __Location_65:import37.Location;
  __MenuController_66:import38.MenuController;
  __ModalController_67:import39.ModalController;
  __PickerController_68:import40.PickerController;
  __PopoverController_69:import41.PopoverController;
  __TapClick_70:import42.TapClick;
  __ToastController_71:import43.ToastController;
  __Translate_72:import44.Translate;
  __TransitionController_73:import45.TransitionController;
  __UrlSerializer_74:any;
  __DeepLinker_75:any;
  __CloudSettingsToken_76:any;
  __DIContainer_77:any;
  __Auth_78:any;
  __Client_79:any;
  __Config_80:any;
  __Deploy_81:any;
  __Push_82:any;
  __User_83:any;
  __FacebookAuth_84:any;
  __GoogleAuth_85:any;
  __AuthData_86:import46.AuthData;
  __Facebook_87:import47.Facebook;
  __Storage_88:import48.Storage;
  constructor(parent:import49.Injector) {
    super(parent,[
      import50.ActionSheetCmpNgFactory,
      import51.AlertCmpNgFactory,
      import52.IonicAppNgFactory,
      import53.LoadingCmpNgFactory,
      import54.ModalCmpNgFactory,
      import55.PickerCmpNgFactory,
      import56.PopoverCmpNgFactory,
      import57.ToastCmpNgFactory,
      import58.MyAppNgFactory,
      import58.MyAppNgFactory,
      import59.LoginNgFactory,
      import60.DashboardNgFactory,
      import61.CategoryNgFactory,
      import62.MembershipNgFactory,
      import52.IonicAppNgFactory
    ]
    ,[import52.IonicAppNgFactory]);
  }
  get _LOCALE_ID_10():any {
    if ((this.__LOCALE_ID_10 == (null as any))) { (this.__LOCALE_ID_10 = 'en-US'); }
    return this.__LOCALE_ID_10;
  }
  get _NgLocalization_11():import10.NgLocaleLocalization {
    if ((this.__NgLocalization_11 == (null as any))) { (this.__NgLocalization_11 = new import10.NgLocaleLocalization(this._LOCALE_ID_10)); }
    return this.__NgLocalization_11;
  }
  get _ApplicationRef_28():any {
    if ((this.__ApplicationRef_28 == (null as any))) { (this.__ApplicationRef_28 = this._ApplicationRef__27); }
    return this.__ApplicationRef_28;
  }
  get _Compiler_29():import15.Compiler {
    if ((this.__Compiler_29 == (null as any))) { (this.__Compiler_29 = new import15.Compiler()); }
    return this.__Compiler_29;
  }
  get _APP_ID_30():any {
    if ((this.__APP_ID_30 == (null as any))) { (this.__APP_ID_30 = import63._appIdRandomProviderFactory()); }
    return this.__APP_ID_30;
  }
  get _DOCUMENT_31():any {
    if ((this.__DOCUMENT_31 == (null as any))) { (this.__DOCUMENT_31 = import4._document()); }
    return this.__DOCUMENT_31;
  }
  get _HAMMER_GESTURE_CONFIG_32():import16.IonicGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_32 == (null as any))) { (this.__HAMMER_GESTURE_CONFIG_32 = new import16.IonicGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_32;
  }
  get _EVENT_MANAGER_PLUGINS_33():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_33 == (null as any))) { (this.__EVENT_MANAGER_PLUGINS_33 = [
      new import64.DomEventsPlugin(),
      new import65.KeyEventsPlugin(),
      new import66.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_32)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_33;
  }
  get _EventManager_34():import17.EventManager {
    if ((this.__EventManager_34 == (null as any))) { (this.__EventManager_34 = new import17.EventManager(this._EVENT_MANAGER_PLUGINS_33,this.parent.get(import67.NgZone))); }
    return this.__EventManager_34;
  }
  get _DomSharedStylesHost_35():import18.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_35 == (null as any))) { (this.__DomSharedStylesHost_35 = new import18.DomSharedStylesHost(this._DOCUMENT_31)); }
    return this.__DomSharedStylesHost_35;
  }
  get _AnimationDriver_36():any {
    if ((this.__AnimationDriver_36 == (null as any))) { (this.__AnimationDriver_36 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_36;
  }
  get _DomRootRenderer_37():import19.DomRootRenderer_ {
    if ((this.__DomRootRenderer_37 == (null as any))) { (this.__DomRootRenderer_37 = new import19.DomRootRenderer_(this._DOCUMENT_31,this._EventManager_34,this._DomSharedStylesHost_35,this._AnimationDriver_36)); }
    return this.__DomRootRenderer_37;
  }
  get _RootRenderer_38():any {
    if ((this.__RootRenderer_38 == (null as any))) { (this.__RootRenderer_38 = import68._createConditionalRootRenderer(this._DomRootRenderer_37,this.parent.get(import68.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_38;
  }
  get _DomSanitizer_39():import20.DomSanitizerImpl {
    if ((this.__DomSanitizer_39 == (null as any))) { (this.__DomSanitizer_39 = new import20.DomSanitizerImpl()); }
    return this.__DomSanitizer_39;
  }
  get _Sanitizer_40():any {
    if ((this.__Sanitizer_40 == (null as any))) { (this.__Sanitizer_40 = this._DomSanitizer_39); }
    return this.__Sanitizer_40;
  }
  get _ViewUtils_41():import21.ViewUtils {
    if ((this.__ViewUtils_41 == (null as any))) { (this.__ViewUtils_41 = new import21.ViewUtils(this._RootRenderer_38,this._APP_ID_30,this._Sanitizer_40)); }
    return this.__ViewUtils_41;
  }
  get _IterableDiffers_42():any {
    if ((this.__IterableDiffers_42 == (null as any))) { (this.__IterableDiffers_42 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_42;
  }
  get _KeyValueDiffers_43():any {
    if ((this.__KeyValueDiffers_43 == (null as any))) { (this.__KeyValueDiffers_43 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_43;
  }
  get _SharedStylesHost_44():any {
    if ((this.__SharedStylesHost_44 == (null as any))) { (this.__SharedStylesHost_44 = this._DomSharedStylesHost_35); }
    return this.__SharedStylesHost_44;
  }
  get _Title_45():import22.Title {
    if ((this.__Title_45 == (null as any))) { (this.__Title_45 = new import22.Title()); }
    return this.__Title_45;
  }
  get _BrowserXhr_46():import23.BrowserXhr {
    if ((this.__BrowserXhr_46 == (null as any))) { (this.__BrowserXhr_46 = new import23.BrowserXhr()); }
    return this.__BrowserXhr_46;
  }
  get _ResponseOptions_47():import24.BaseResponseOptions {
    if ((this.__ResponseOptions_47 == (null as any))) { (this.__ResponseOptions_47 = new import24.BaseResponseOptions()); }
    return this.__ResponseOptions_47;
  }
  get _XSRFStrategy_48():any {
    if ((this.__XSRFStrategy_48 == (null as any))) { (this.__XSRFStrategy_48 = import5._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_48;
  }
  get _XHRBackend_49():import25.XHRBackend {
    if ((this.__XHRBackend_49 == (null as any))) { (this.__XHRBackend_49 = new import25.XHRBackend(this._BrowserXhr_46,this._ResponseOptions_47,this._XSRFStrategy_48)); }
    return this.__XHRBackend_49;
  }
  get _RequestOptions_50():import26.BaseRequestOptions {
    if ((this.__RequestOptions_50 == (null as any))) { (this.__RequestOptions_50 = new import26.BaseRequestOptions()); }
    return this.__RequestOptions_50;
  }
  get _Http_51():any {
    if ((this.__Http_51 == (null as any))) { (this.__Http_51 = import5.httpFactory(this._XHRBackend_49,this._RequestOptions_50)); }
    return this.__Http_51;
  }
  get _RadioControlRegistry_52():import27.RadioControlRegistry {
    if ((this.__RadioControlRegistry_52 == (null as any))) { (this.__RadioControlRegistry_52 = new import27.RadioControlRegistry()); }
    return this.__RadioControlRegistry_52;
  }
  get _FormBuilder_53():import28.FormBuilder {
    if ((this.__FormBuilder_53 == (null as any))) { (this.__FormBuilder_53 = new import28.FormBuilder()); }
    return this.__FormBuilder_53;
  }
  get _AppRootToken_54():any {
    if ((this.__AppRootToken_54 == (null as any))) { (this.__AppRootToken_54 = import69.MyApp); }
    return this.__AppRootToken_54;
  }
  get _DeepLinkConfigToken_55():any {
    if ((this.__DeepLinkConfigToken_55 == (null as any))) { (this.__DeepLinkConfigToken_55 = (null as any)); }
    return this.__DeepLinkConfigToken_55;
  }
  get _ActionSheetController_56():import29.ActionSheetController {
    if ((this.__ActionSheetController_56 == (null as any))) { (this.__ActionSheetController_56 = new import29.ActionSheetController(this._App_23)); }
    return this.__ActionSheetController_56;
  }
  get _AlertController_57():import30.AlertController {
    if ((this.__AlertController_57 == (null as any))) { (this.__AlertController_57 = new import30.AlertController(this._App_23)); }
    return this.__AlertController_57;
  }
  get _Events_58():import31.Events {
    if ((this.__Events_58 == (null as any))) { (this.__Events_58 = new import31.Events()); }
    return this.__Events_58;
  }
  get _Form_59():import32.Form {
    if ((this.__Form_59 == (null as any))) { (this.__Form_59 = new import32.Form()); }
    return this.__Form_59;
  }
  get _Haptic_60():import33.Haptic {
    if ((this.__Haptic_60 == (null as any))) { (this.__Haptic_60 = new import33.Haptic(this._Platform_21)); }
    return this.__Haptic_60;
  }
  get _GestureController_61():import34.GestureController {
    if ((this.__GestureController_61 == (null as any))) { (this.__GestureController_61 = new import34.GestureController(this._App_23)); }
    return this.__GestureController_61;
  }
  get _Keyboard_62():import35.Keyboard {
    if ((this.__Keyboard_62 == (null as any))) { (this.__Keyboard_62 = new import35.Keyboard(this._Config_22,this._Form_59,this.parent.get(import67.NgZone))); }
    return this.__Keyboard_62;
  }
  get _LoadingController_63():import36.LoadingController {
    if ((this.__LoadingController_63 == (null as any))) { (this.__LoadingController_63 = new import36.LoadingController(this._App_23)); }
    return this.__LoadingController_63;
  }
  get _LocationStrategy_64():any {
    if ((this.__LocationStrategy_64 == (null as any))) { (this.__LocationStrategy_64 = import8.provideLocationStrategy(this.parent.get(import70.PlatformLocation),this.parent.get(import71.APP_BASE_HREF,(null as any)),this._Config_22)); }
    return this.__LocationStrategy_64;
  }
  get _Location_65():import37.Location {
    if ((this.__Location_65 == (null as any))) { (this.__Location_65 = new import37.Location(this._LocationStrategy_64)); }
    return this.__Location_65;
  }
  get _MenuController_66():import38.MenuController {
    if ((this.__MenuController_66 == (null as any))) { (this.__MenuController_66 = new import38.MenuController()); }
    return this.__MenuController_66;
  }
  get _ModalController_67():import39.ModalController {
    if ((this.__ModalController_67 == (null as any))) { (this.__ModalController_67 = new import39.ModalController(this._App_23)); }
    return this.__ModalController_67;
  }
  get _PickerController_68():import40.PickerController {
    if ((this.__PickerController_68 == (null as any))) { (this.__PickerController_68 = new import40.PickerController(this._App_23)); }
    return this.__PickerController_68;
  }
  get _PopoverController_69():import41.PopoverController {
    if ((this.__PopoverController_69 == (null as any))) { (this.__PopoverController_69 = new import41.PopoverController(this._App_23)); }
    return this.__PopoverController_69;
  }
  get _TapClick_70():import42.TapClick {
    if ((this.__TapClick_70 == (null as any))) { (this.__TapClick_70 = new import42.TapClick(this._Config_22,this._App_23,this.parent.get(import67.NgZone))); }
    return this.__TapClick_70;
  }
  get _ToastController_71():import43.ToastController {
    if ((this.__ToastController_71 == (null as any))) { (this.__ToastController_71 = new import43.ToastController(this._App_23)); }
    return this.__ToastController_71;
  }
  get _Translate_72():import44.Translate {
    if ((this.__Translate_72 == (null as any))) { (this.__Translate_72 = new import44.Translate()); }
    return this.__Translate_72;
  }
  get _TransitionController_73():import45.TransitionController {
    if ((this.__TransitionController_73 == (null as any))) { (this.__TransitionController_73 = new import45.TransitionController(this._Config_22)); }
    return this.__TransitionController_73;
  }
  get _UrlSerializer_74():any {
    if ((this.__UrlSerializer_74 == (null as any))) { (this.__UrlSerializer_74 = import72.setupUrlSerializer(this._DeepLinkConfigToken_55)); }
    return this.__UrlSerializer_74;
  }
  get _DeepLinker_75():any {
    if ((this.__DeepLinker_75 == (null as any))) { (this.__DeepLinker_75 = import73.setupDeepLinker(this._App_23,this._UrlSerializer_74,this._Location_65)); }
    return this.__DeepLinker_75;
  }
  get _CloudSettingsToken_76():any {
    if ((this.__CloudSettingsToken_76 == (null as any))) { (this.__CloudSettingsToken_76 = {
      core: {app_id: '89423043'},
      push: {
        sender_id: '82070365426',
        pluginConfig: {
          ios: {
            alert: true,
            badge: true,
            sound: true
          }
          ,
          android: {iconColor: '#343434'}
        }

      }

    }
    ); }
    return this.__CloudSettingsToken_76;
  }
  get _DIContainer_77():any {
    if ((this.__DIContainer_77 == (null as any))) { (this.__DIContainer_77 = import9.provideContainer(this._CloudSettingsToken_76)); }
    return this.__DIContainer_77;
  }
  get _Auth_78():any {
    if ((this.__Auth_78 == (null as any))) { (this.__Auth_78 = import9.provideAuth(this._DIContainer_77)); }
    return this.__Auth_78;
  }
  get _Client_79():any {
    if ((this.__Client_79 == (null as any))) { (this.__Client_79 = import9.provideClient(this._DIContainer_77)); }
    return this.__Client_79;
  }
  get _Config_80():any {
    if ((this.__Config_80 == (null as any))) { (this.__Config_80 = import9.provideConfig(this._DIContainer_77)); }
    return this.__Config_80;
  }
  get _Deploy_81():any {
    if ((this.__Deploy_81 == (null as any))) { (this.__Deploy_81 = import9.provideDeploy(this._DIContainer_77)); }
    return this.__Deploy_81;
  }
  get _Push_82():any {
    if ((this.__Push_82 == (null as any))) { (this.__Push_82 = import9.providePush(this._DIContainer_77)); }
    return this.__Push_82;
  }
  get _User_83():any {
    if ((this.__User_83 == (null as any))) { (this.__User_83 = import9.provideUser(this._DIContainer_77)); }
    return this.__User_83;
  }
  get _FacebookAuth_84():any {
    if ((this.__FacebookAuth_84 == (null as any))) { (this.__FacebookAuth_84 = import9.provideFacebookAuth(this._DIContainer_77)); }
    return this.__FacebookAuth_84;
  }
  get _GoogleAuth_85():any {
    if ((this.__GoogleAuth_85 == (null as any))) { (this.__GoogleAuth_85 = import9.provideGoogleAuth(this._DIContainer_77)); }
    return this.__GoogleAuth_85;
  }
  get _AuthData_86():import46.AuthData {
    if ((this.__AuthData_86 == (null as any))) { (this.__AuthData_86 = new import46.AuthData()); }
    return this.__AuthData_86;
  }
  get _Facebook_87():import47.Facebook {
    if ((this.__Facebook_87 == (null as any))) { (this.__Facebook_87 = new import47.Facebook()); }
    return this.__Facebook_87;
  }
  get _Storage_88():import48.Storage {
    if ((this.__Storage_88 == (null as any))) { (this.__Storage_88 = new import48.Storage()); }
    return this.__Storage_88;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._HttpModule_3 = new import5.HttpModule();
    this._InternalFormsSharedModule_4 = new import6.InternalFormsSharedModule();
    this._FormsModule_5 = new import7.FormsModule();
    this._ReactiveFormsModule_6 = new import7.ReactiveFormsModule();
    this._IonicModule_7 = new import8.IonicModule();
    this._CloudModule_8 = new import9.CloudModule();
    this._AppModule_9 = new import1.AppModule();
    this._ErrorHandler_12 = import4.errorHandler();
    this._ConfigToken_13 = (null as any);
    this._UrlToken_14 = import8.provideLocationHref();
    this._QueryParams_15 = import74.setupQueryParams(this._UrlToken_14);
    this._PlatformConfigToken_16 = import75.providePlatformConfigs();
    this._UserAgentToken_17 = import8.provideUserAgent();
    this._NavigatorPlatformToken_18 = import8.provideNavigatorPlatform();
    this._DocumentDirToken_19 = import8.provideDocumentDirection();
    this._DocLangToken_20 = import8.provideDocumentLang();
    this._Platform_21 = import76.setupPlatform(this._PlatformConfigToken_16,this._QueryParams_15,this._UserAgentToken_17,this._NavigatorPlatformToken_18,this._DocumentDirToken_19,this._DocLangToken_20,this.parent.get(import67.NgZone));
    this._Config_22 = import77.setupConfig(this._ConfigToken_13,this._QueryParams_15,this._Platform_21);
    this._App_23 = new import11.App(this._Config_22,this._Platform_21);
    this._APP_INITIALIZER_24 = [
      import78.registerModeConfigs(this._Config_22),
      import79.registerTransitions(this._Config_22),
      import31.setupProvideEvents(this._Platform_21),
      import42.setupTapClick(this._Config_22,this._App_23,this.parent.get(import67.NgZone))
    ]
    ;
    this._ApplicationInitStatus_25 = new import12.ApplicationInitStatus(this._APP_INITIALIZER_24);
    this._Testability_26 = new import13.Testability(this.parent.get(import67.NgZone));
    this._ApplicationRef__27 = new import14.ApplicationRef_(this.parent.get(import67.NgZone),this.parent.get(import80.Console),this,this._ErrorHandler_12,this,this._ApplicationInitStatus_25,this.parent.get(import13.TestabilityRegistry,(null as any)),this._Testability_26);
    return this._AppModule_9;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.HttpModule)) { return this._HttpModule_3; }
    if ((token === import6.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_4; }
    if ((token === import7.FormsModule)) { return this._FormsModule_5; }
    if ((token === import7.ReactiveFormsModule)) { return this._ReactiveFormsModule_6; }
    if ((token === import8.IonicModule)) { return this._IonicModule_7; }
    if ((token === import9.CloudModule)) { return this._CloudModule_8; }
    if ((token === import1.AppModule)) { return this._AppModule_9; }
    if ((token === import81.LOCALE_ID)) { return this._LOCALE_ID_10; }
    if ((token === import10.NgLocalization)) { return this._NgLocalization_11; }
    if ((token === import82.ErrorHandler)) { return this._ErrorHandler_12; }
    if ((token === import77.ConfigToken)) { return this._ConfigToken_13; }
    if ((token === import74.UrlToken)) { return this._UrlToken_14; }
    if ((token === import74.QueryParams)) { return this._QueryParams_15; }
    if ((token === import75.PlatformConfigToken)) { return this._PlatformConfigToken_16; }
    if ((token === import76.UserAgentToken)) { return this._UserAgentToken_17; }
    if ((token === import76.NavigatorPlatformToken)) { return this._NavigatorPlatformToken_18; }
    if ((token === import76.DocumentDirToken)) { return this._DocumentDirToken_19; }
    if ((token === import76.DocLangToken)) { return this._DocLangToken_20; }
    if ((token === import76.Platform)) { return this._Platform_21; }
    if ((token === import77.Config)) { return this._Config_22; }
    if ((token === import11.App)) { return this._App_23; }
    if ((token === import12.APP_INITIALIZER)) { return this._APP_INITIALIZER_24; }
    if ((token === import12.ApplicationInitStatus)) { return this._ApplicationInitStatus_25; }
    if ((token === import13.Testability)) { return this._Testability_26; }
    if ((token === import14.ApplicationRef_)) { return this._ApplicationRef__27; }
    if ((token === import14.ApplicationRef)) { return this._ApplicationRef_28; }
    if ((token === import15.Compiler)) { return this._Compiler_29; }
    if ((token === import63.APP_ID)) { return this._APP_ID_30; }
    if ((token === import83.DOCUMENT)) { return this._DOCUMENT_31; }
    if ((token === import66.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_32; }
    if ((token === import17.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_33; }
    if ((token === import17.EventManager)) { return this._EventManager_34; }
    if ((token === import18.DomSharedStylesHost)) { return this._DomSharedStylesHost_35; }
    if ((token === import84.AnimationDriver)) { return this._AnimationDriver_36; }
    if ((token === import19.DomRootRenderer)) { return this._DomRootRenderer_37; }
    if ((token === import85.RootRenderer)) { return this._RootRenderer_38; }
    if ((token === import20.DomSanitizer)) { return this._DomSanitizer_39; }
    if ((token === import86.Sanitizer)) { return this._Sanitizer_40; }
    if ((token === import21.ViewUtils)) { return this._ViewUtils_41; }
    if ((token === import87.IterableDiffers)) { return this._IterableDiffers_42; }
    if ((token === import88.KeyValueDiffers)) { return this._KeyValueDiffers_43; }
    if ((token === import18.SharedStylesHost)) { return this._SharedStylesHost_44; }
    if ((token === import22.Title)) { return this._Title_45; }
    if ((token === import23.BrowserXhr)) { return this._BrowserXhr_46; }
    if ((token === import24.ResponseOptions)) { return this._ResponseOptions_47; }
    if ((token === import89.XSRFStrategy)) { return this._XSRFStrategy_48; }
    if ((token === import25.XHRBackend)) { return this._XHRBackend_49; }
    if ((token === import26.RequestOptions)) { return this._RequestOptions_50; }
    if ((token === import90.Http)) { return this._Http_51; }
    if ((token === import27.RadioControlRegistry)) { return this._RadioControlRegistry_52; }
    if ((token === import28.FormBuilder)) { return this._FormBuilder_53; }
    if ((token === import91.AppRootToken)) { return this._AppRootToken_54; }
    if ((token === import72.DeepLinkConfigToken)) { return this._DeepLinkConfigToken_55; }
    if ((token === import29.ActionSheetController)) { return this._ActionSheetController_56; }
    if ((token === import30.AlertController)) { return this._AlertController_57; }
    if ((token === import31.Events)) { return this._Events_58; }
    if ((token === import32.Form)) { return this._Form_59; }
    if ((token === import33.Haptic)) { return this._Haptic_60; }
    if ((token === import34.GestureController)) { return this._GestureController_61; }
    if ((token === import35.Keyboard)) { return this._Keyboard_62; }
    if ((token === import36.LoadingController)) { return this._LoadingController_63; }
    if ((token === import71.LocationStrategy)) { return this._LocationStrategy_64; }
    if ((token === import37.Location)) { return this._Location_65; }
    if ((token === import38.MenuController)) { return this._MenuController_66; }
    if ((token === import39.ModalController)) { return this._ModalController_67; }
    if ((token === import40.PickerController)) { return this._PickerController_68; }
    if ((token === import41.PopoverController)) { return this._PopoverController_69; }
    if ((token === import42.TapClick)) { return this._TapClick_70; }
    if ((token === import43.ToastController)) { return this._ToastController_71; }
    if ((token === import44.Translate)) { return this._Translate_72; }
    if ((token === import45.TransitionController)) { return this._TransitionController_73; }
    if ((token === import72.UrlSerializer)) { return this._UrlSerializer_74; }
    if ((token === import73.DeepLinker)) { return this._DeepLinker_75; }
    if ((token === import9.CloudSettingsToken)) { return this._CloudSettingsToken_76; }
    if ((token === import9.DIContainer)) { return this._DIContainer_77; }
    if ((token === import9.Auth)) { return this._Auth_78; }
    if ((token === import9.Client)) { return this._Client_79; }
    if ((token === import9.Config)) { return this._Config_80; }
    if ((token === import9.Deploy)) { return this._Deploy_81; }
    if ((token === import9.Push)) { return this._Push_82; }
    if ((token === import9.User)) { return this._User_83; }
    if ((token === import9.FacebookAuth)) { return this._FacebookAuth_84; }
    if ((token === import9.GoogleAuth)) { return this._GoogleAuth_85; }
    if ((token === import46.AuthData)) { return this._AuthData_86; }
    if ((token === import47.Facebook)) { return this._Facebook_87; }
    if ((token === import48.Storage)) { return this._Storage_88; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__27.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);