/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './dashboard';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from 'ionic-angular/components/toolbar/toolbar';
import * as import12 from 'ionic-angular/components/navbar/navbar';
import * as import13 from 'ionic-angular/components/menu/menu-toggle';
import * as import14 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import15 from '@angular/core/src/linker/query_list';
import * as import16 from '@angular/common/src/directives/ng_style';
import * as import17 from 'ionic-angular/components/icon/icon';
import * as import18 from 'ionic-angular/components/content/content';
import * as import19 from 'ionic-angular/config/config';
import * as import20 from '@angular/core/src/linker/element_ref';
import * as import21 from 'ionic-angular/navigation/view-controller';
import * as import22 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import23 from 'ionic-angular/components/app/app';
import * as import24 from 'ionic-angular/components/menu/menu-controller';
import * as import25 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import26 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import27 from 'ionic-angular/util/keyboard';
import * as import28 from '@angular/core/src/zone/ng_zone';
import * as import29 from 'ionic-angular/components/tabs/tabs';
var renderType_Dashboard_Host:import0.RenderComponentType = (null as any);
class _View_Dashboard_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Dashboard_0_4:import3.Dashboard;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_Dashboard_Host0,renderType_Dashboard_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-dashboard',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_Dashboard0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Dashboard_0_4 = new import3.Dashboard(this.parentInjector.get(import8.NavController));
    this._appEl_0.initComponent(this._Dashboard_0_4,([] as any[]),compView_0);
    compView_0.create(this._Dashboard_0_4,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.Dashboard) && (0 === requestNodeIndex))) { return this._Dashboard_0_4; }
    return notFoundResult;
  }
}
function viewFactory_Dashboard_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_Dashboard_Host === (null as any))) { (renderType_Dashboard_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_Dashboard_Host0(viewUtils,parentInjector,declarationEl);
}
export const DashboardNgFactory:import10.ComponentFactory<import3.Dashboard> = new import10.ComponentFactory<import3.Dashboard>('page-dashboard',viewFactory_Dashboard_Host0,import3.Dashboard);
const styles_Dashboard:any[] = ([] as any[]);
var renderType_Dashboard:import0.RenderComponentType = (null as any);
class _View_Dashboard0 extends import1.AppView<import3.Dashboard> {
  _text_0:any;
  _el_1:any;
  _Header_1_3:import11.Header;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import2.AppElement;
  _Navbar_3_4:import12.Navbar;
  _text_4:any;
  _el_5:any;
  _MenuToggle_5_3:import13.MenuToggle;
  _ToolbarItem_5_4:import14.ToolbarItem;
  _query_Button_5_0:import15.QueryList<any>;
  _el_6:any;
  _NgStyle_6_3:import16.NgStyle;
  _Icon_6_4:import17.Icon;
  _text_7:any;
  _el_8:any;
  _MenuToggle_8_3:import13.MenuToggle;
  _ToolbarItem_8_4:import14.ToolbarItem;
  _query_Button_8_0:import15.QueryList<any>;
  _el_9:any;
  _NgStyle_9_3:import16.NgStyle;
  _Icon_9_4:import17.Icon;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  /*private*/ _appEl_13:import2.AppElement;
  _Content_13_4:import18.Content;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _el_30:any;
  _el_31:any;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  _el_35:any;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  _el_39:any;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  _el_43:any;
  _text_44:any;
  _el_45:any;
  _el_46:any;
  _text_47:any;
  _text_48:any;
  _el_49:any;
  _el_50:any;
  _text_51:any;
  _text_52:any;
  _el_53:any;
  _el_54:any;
  _text_55:any;
  _text_56:any;
  _text_57:any;
  _el_58:any;
  _text_59:any;
  _el_60:any;
  _text_61:any;
  _text_62:any;
  _text_63:any;
  _text_64:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  _map_0:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  _map_1:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_Dashboard0,renderType_Dashboard,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this.renderer.setElementAttribute(this._el_1,'class','header');
    this._Header_1_3 = new import11.Header(this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_1),this.renderer,this.parentInjector.get(import21.ViewController,(null as any)));
    this._text_2 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','toolbar');
    this._appEl_3 = new import2.AppElement(3,1,this,this._el_3);
    var compView_3:any = import22.viewFactory_Navbar0(this.viewUtils,this.injector(3),this._appEl_3);
    this._Navbar_3_4 = new import12.Navbar(this.parentInjector.get(import23.App),this.parentInjector.get(import21.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_3),this.renderer);
    this._appEl_3.initComponent(this._Navbar_3_4,([] as any[]),compView_3);
    this._text_4 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_5,'left','');
    this.renderer.setElementAttribute(this._el_5,'menuToggle','');
    this._MenuToggle_5_3 = new import13.MenuToggle(this.parentInjector.get(import24.MenuController),new import20.ElementRef(this._el_5),this.parentInjector.get(import21.ViewController,(null as any)),this._Navbar_3_4);
    this._ToolbarItem_5_4 = new import14.ToolbarItem(this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_5),this.renderer,this.parentInjector.get(import11.Toolbar,(null as any)),this._Navbar_3_4);
    this._query_Button_5_0 = new import15.QueryList<any>();
    this._el_6 = this.renderer.createElement(this._el_5,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_6,'name','menu');
    this.renderer.setElementAttribute(this._el_6,'role','img');
    this._NgStyle_6_3 = new import16.NgStyle(this.parentInjector.get(import25.KeyValueDiffers),new import20.ElementRef(this._el_6),this.renderer);
    this._Icon_6_4 = new import17.Icon(this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_6),this.renderer);
    this._text_7 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_8 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_8,'menuToggle','');
    this.renderer.setElementAttribute(this._el_8,'right','');
    this._MenuToggle_8_3 = new import13.MenuToggle(this.parentInjector.get(import24.MenuController),new import20.ElementRef(this._el_8),this.parentInjector.get(import21.ViewController,(null as any)),this._Navbar_3_4);
    this._ToolbarItem_8_4 = new import14.ToolbarItem(this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_8),this.renderer,this.parentInjector.get(import11.Toolbar,(null as any)),this._Navbar_3_4);
    this._query_Button_8_0 = new import15.QueryList<any>();
    this._el_9 = this.renderer.createElement(this._el_8,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_9,'name','ios-notifications');
    this.renderer.setElementAttribute(this._el_9,'role','img');
    this._NgStyle_9_3 = new import16.NgStyle(this.parentInjector.get(import25.KeyValueDiffers),new import20.ElementRef(this._el_9),this.renderer);
    this._Icon_9_4 = new import17.Icon(this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_9),this.renderer);
    this._text_10 = this.renderer.createText((null as any),'\n    ',(null as any));
    compView_3.create(this._Navbar_3_4,[
      ([] as any[]).concat([
        this._el_5,
        this._el_8
      ]
      ),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_4,
        this._text_7,
        this._text_10
      ]
      )
    ]
    ,(null as any));
    this._text_11 = this.renderer.createText(this._el_1,'\n',(null as any));
    this._text_12 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._el_13 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','container');
    this._appEl_13 = new import2.AppElement(13,(null as any),this,this._el_13);
    var compView_13:any = import26.viewFactory_Content0(this.viewUtils,this.injector(13),this._appEl_13);
    this._Content_13_4 = new import18.Content(this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_13),this.renderer,this.parentInjector.get(import23.App),this.parentInjector.get(import27.Keyboard),this.parentInjector.get(import28.NgZone),this.parentInjector.get(import21.ViewController,(null as any)),this.parentInjector.get(import29.Tabs,(null as any)));
    this._appEl_13.initComponent(this._Content_13_4,([] as any[]),compView_13);
    this._text_14 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_15 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_15,'class','top-bar');
    this._text_16 = this.renderer.createText(this._el_15,'\n        ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_15,'img',(null as any));
    this.renderer.setElementAttribute(this._el_17,'class','vkirirom-img');
    this.renderer.setElementAttribute(this._el_17,'src','img/vkirirom_logo.svg');
    this._text_18 = this.renderer.createText(this._el_15,'\n    ',(null as any));
    this._text_19 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_20 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_20,'class','noti-bar');
    this._text_21 = this.renderer.createText(this._el_20,'\n        ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_20,'p',(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'Please assemble at Football Field',(null as any));
    this._text_24 = this.renderer.createText(this._el_20,'\n    ',(null as any));
    this._text_25 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_26 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_26,'class','dashboard-action');
    this._text_27 = this.renderer.createText(this._el_26,'\n        ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_26,'div',(null as any));
    this.renderer.setElementAttribute(this._el_28,'class','first-row');
    this._text_29 = this.renderer.createText(this._el_28,'\n            ',(null as any));
    this._el_30 = this.renderer.createElement(this._el_28,'button',(null as any));
    this.renderer.setElementAttribute(this._el_30,'class','service-btn');
    this._el_31 = this.renderer.createElement(this._el_30,'img',(null as any));
    this.renderer.setElementAttribute(this._el_31,'src','img/service-icon.svg');
    this._text_32 = this.renderer.createText(this._el_30,'Service',(null as any));
    this._text_33 = this.renderer.createText(this._el_28,'\n            ',(null as any));
    this._el_34 = this.renderer.createElement(this._el_28,'button',(null as any));
    this.renderer.setElementAttribute(this._el_34,'class','member-btn');
    this._el_35 = this.renderer.createElement(this._el_34,'img',(null as any));
    this.renderer.setElementAttribute(this._el_35,'src','img/card-icon.svg');
    this._text_36 = this.renderer.createText(this._el_34,'Membership Card',(null as any));
    this._text_37 = this.renderer.createText(this._el_28,'\n            ',(null as any));
    this._el_38 = this.renderer.createElement(this._el_28,'button',(null as any));
    this.renderer.setElementAttribute(this._el_38,'class','map-btn');
    this._el_39 = this.renderer.createElement(this._el_38,'img',(null as any));
    this.renderer.setElementAttribute(this._el_39,'src','img/map-icon.svg');
    this._text_40 = this.renderer.createText(this._el_38,'vMap',(null as any));
    this._text_41 = this.renderer.createText(this._el_28,'\n        ',(null as any));
    this._text_42 = this.renderer.createText(this._el_26,'\n        ',(null as any));
    this._el_43 = this.renderer.createElement(this._el_26,'div',(null as any));
    this.renderer.setElementAttribute(this._el_43,'class','second-row');
    this._text_44 = this.renderer.createText(this._el_43,'\n            ',(null as any));
    this._el_45 = this.renderer.createElement(this._el_43,'button',(null as any));
    this.renderer.setElementAttribute(this._el_45,'class','service-btn');
    this._el_46 = this.renderer.createElement(this._el_45,'img',(null as any));
    this.renderer.setElementAttribute(this._el_46,'src','img/chat-icon.svg');
    this._text_47 = this.renderer.createText(this._el_45,'Chat',(null as any));
    this._text_48 = this.renderer.createText(this._el_43,'\n            ',(null as any));
    this._el_49 = this.renderer.createElement(this._el_43,'button',(null as any));
    this.renderer.setElementAttribute(this._el_49,'class','member-btn');
    this._el_50 = this.renderer.createElement(this._el_49,'img',(null as any));
    this.renderer.setElementAttribute(this._el_50,'src','img/media-icon.svg');
    this._text_51 = this.renderer.createText(this._el_49,'Media',(null as any));
    this._text_52 = this.renderer.createText(this._el_43,'\n            ',(null as any));
    this._el_53 = this.renderer.createElement(this._el_43,'button',(null as any));
    this.renderer.setElementAttribute(this._el_53,'class','map-btn');
    this._el_54 = this.renderer.createElement(this._el_53,'img',(null as any));
    this.renderer.setElementAttribute(this._el_54,'src','img/about-icon.svg');
    this._text_55 = this.renderer.createText(this._el_53,'About Us',(null as any));
    this._text_56 = this.renderer.createText(this._el_43,'\n        ',(null as any));
    this._text_57 = this.renderer.createText(this._el_26,'\n        ',(null as any));
    this._el_58 = this.renderer.createElement(this._el_26,'div',(null as any));
    this.renderer.setElementAttribute(this._el_58,'class','emergency');
    this._text_59 = this.renderer.createText(this._el_58,'\n            ',(null as any));
    this._el_60 = this.renderer.createElement(this._el_58,'button',(null as any));
    this._text_61 = this.renderer.createText(this._el_60,'EMERGENCY SOS',(null as any));
    this._text_62 = this.renderer.createText(this._el_58,'\n        ',(null as any));
    this._text_63 = this.renderer.createText(this._el_26,'\n    ',(null as any));
    this._text_64 = this.renderer.createText((null as any),'\n',(null as any));
    compView_13.create(this._Content_13_4,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_14,
        this._el_15,
        this._text_19,
        this._el_20,
        this._text_25,
        this._el_26,
        this._text_64
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_5,'click',this.eventHandler(this._handle_click_5_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._map_0 = import4.pureProxy1((p0:any):{[key: string]:any} => {
      return {color: p0};
    });
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_8,'click',this.eventHandler(this._handle_click_8_0.bind(this)));
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._map_1 = import4.pureProxy1((p0:any):{[key: string]:any} => {
      return {color: p0};
    });
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_34,'click',this.eventHandler(this._handle_click_34_0.bind(this)));
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._el_45,
      this._el_46,
      this._text_47,
      this._text_48,
      this._el_49,
      this._el_50,
      this._text_51,
      this._text_52,
      this._el_53,
      this._el_54,
      this._text_55,
      this._text_56,
      this._text_57,
      this._el_58,
      this._text_59,
      this._el_60,
      this._text_61,
      this._text_62,
      this._text_63,
      this._text_64
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import16.NgStyle) && (6 === requestNodeIndex))) { return this._NgStyle_6_3; }
    if (((token === import17.Icon) && (6 === requestNodeIndex))) { return this._Icon_6_4; }
    if (((token === import13.MenuToggle) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._MenuToggle_5_3; }
    if (((token === import14.ToolbarItem) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._ToolbarItem_5_4; }
    if (((token === import16.NgStyle) && (9 === requestNodeIndex))) { return this._NgStyle_9_3; }
    if (((token === import17.Icon) && (9 === requestNodeIndex))) { return this._Icon_9_4; }
    if (((token === import13.MenuToggle) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._MenuToggle_8_3; }
    if (((token === import14.ToolbarItem) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._ToolbarItem_8_4; }
    if (((token === import12.Navbar) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._Navbar_3_4; }
    if (((token === import11.Header) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._Header_1_3; }
    if (((token === import18.Content) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 64)))) { return this._Content_13_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_3:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._MenuToggle_5_3.menuToggle = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_5:any = this._map_0('white');
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._NgStyle_6_3.ngStyle = currVal_5;
      this._expr_5 = currVal_5;
    }
    if (!throwOnChange) { this._NgStyle_6_3.ngDoCheck(); }
    const currVal_6:any = 'menu';
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._Icon_6_4.name = currVal_6;
      this._expr_6 = currVal_6;
    }
    const currVal_9:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._MenuToggle_8_3.menuToggle = currVal_9;
      this._expr_9 = currVal_9;
    }
    const currVal_11:any = this._map_1('white');
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._NgStyle_9_3.ngStyle = currVal_11;
      this._expr_11 = currVal_11;
    }
    if (!throwOnChange) { this._NgStyle_9_3.ngDoCheck(); }
    const currVal_12:any = 'ios-notifications';
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._Icon_9_4.name = currVal_12;
      this._expr_12 = currVal_12;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_13_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_5_0.dirty) {
        this._query_Button_5_0.reset(([] as any[]));
        this._ToolbarItem_5_4._buttons = this._query_Button_5_0;
        this._query_Button_5_0.notifyOnChanges();
      }
      if (this._query_Button_8_0.dirty) {
        this._query_Button_8_0.reset(([] as any[]));
        this._ToolbarItem_8_4._buttons = this._query_Button_8_0;
        this._query_Button_8_0.notifyOnChanges();
      }
    }
    const currVal_0:any = this._Navbar_3_4._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_3,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_3_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_3,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_4:any = this._MenuToggle_5_3.isHidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_5,'hidden',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_7:any = this._Icon_6_4._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_6,'hide',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_10:any = this._MenuToggle_8_3.isHidden;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementProperty(this._el_8,'hidden',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_13:any = this._Icon_9_4._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_9,'hide',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = this._Content_13_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_13,'statusbar-padding',currVal_14);
      this._expr_14 = currVal_14;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_3_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_6_4.ngOnDestroy();
    this._Icon_9_4.ngOnDestroy();
    this._Content_13_4.ngOnDestroy();
  }
  private _handle_click_5_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_5_3.toggle()) !== false);
    return (true && pd_0);
  }
  private _handle_click_8_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_8_3.toggle()) !== false);
    return (true && pd_0);
  }
  private _handle_click_34_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.navigate()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_Dashboard0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.Dashboard> {
  if ((renderType_Dashboard === (null as any))) { (renderType_Dashboard = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,styles_Dashboard,{})); }
  return new _View_Dashboard0(viewUtils,parentInjector,declarationEl);
}